import { AssetType, type GameState } from '../types';
import { tl } from '../i18n/town';
import { LIFESTYLE_OPTS } from '../constants';
import { calculateMonthlyCashFlowEstimate } from './gameLogic';
import { savingsBalance } from './townActivities';
import { reputationOf } from './townCafe';
import { promotionOutlook } from './townWork';
import { studyPlan } from './townCollege';
import { household } from './townFamily';
import { offers } from './townInsurance';

// Rosa, the neighbour on the promenade bench, reads the player's actual numbers and says the
// one or two things a sensible friend would say. Rules are ordered by urgency; each returns a
// short observation with an optional place to go. Nothing here moves money.
export type Advice = { id: string; tone: 'warn' | 'tip' | 'good'; title: string; text: string; place?: 'bank' | 'exchange' | 'property' | 'cafe' | 'home' | 'board' | 'work' | 'college' };

const money = (n: number) => (n < 0 ? '-' : '') + '$' + Math.abs(Math.round(n)).toLocaleString('en-US');
export function adviseFrom(state: GameState): Advice[] {
  const flow = calculateMonthlyCashFlowEstimate(state), expenses = Math.max(1, flow.expenses), income = Math.max(1, flow.income);
  const invested = state.assets.filter(a => a.type !== AssetType.SAVINGS && a.quantity > 0), investedValue = invested.reduce((s, a) => s + a.value * a.quantity, 0);
  const crypto = invested.filter(a => a.type === AssetType.CRYPTO).reduce((s, a) => s + a.value * a.quantity, 0);
  const savings = savingsBalance(state), buffer = state.cash + savings;
  const expensiveDebt = state.liabilities.filter(l => l.interestRate >= .12 && l.balance > 0), expensiveBalance = expensiveDebt.reduce((s, l) => s + l.balance, 0);
  const lifestyleCost = LIFESTYLE_OPTS[state.lifestyle]?.cost ?? 0;
  const passiveShare = flow.passive / expenses;
  const out: Advice[] = [];
  if (state.hasWon) out.push({ id: 'won', tone: 'good', title: tl('You did it. Your money works so you do not have to.','Lo lograste. Tu dinero trabaja para que tú no tengas que hacerlo.'), text: `${tl('Passive income of','Los ingresos pasivos de')} ${money(flow.passive)} ${tl('a month covers','al mes cubren')} ${money(expenses)} ${tl('of bills with room to spare. The trap now is lifestyle creep: every upgrade raises the bar your investments have to clear. Keep the reserve, keep investing, and enjoy the square.','de facturas con margen. La trampa ahora es inflar el estilo de vida: cada mejora sube la vara que tus inversiones deben superar. Conserva la reserva, sigue invirtiendo y disfruta la plaza.')}` });
  if (state.cash < expenses) out.push({ id: 'thin', tone: 'warn', title: tl('Your cash is thinner than one month of bills.','Tu efectivo no cubre ni un mes de facturas.'), text: `${tl('You have','Tienes')} ${money(state.cash)} ${tl('against','frente a')} ${money(expenses)} ${tl('of monthly costs. One surprise and you are borrowing. Park the next paycheque before anything else.','de gastos mensuales. Una sorpresa y estarás pidiendo prestado. Guarda el próximo sueldo antes que nada.')}`, place: 'bank' });
  if (expensiveBalance > 0 && investedValue > 0) out.push({ id: 'expensive-debt', tone: 'warn', title: `${tl('You are paying','Estás pagando')} ${Math.round(Math.max(...expensiveDebt.map(l => l.interestRate)) * 100)}% ${tl('interest while hoping for 10% returns.','de interés mientras esperas rendimientos del 10%.')}`, text: `${money(expensiveBalance)} ${tl('of expensive debt is a guaranteed loss every month. Clearing it beats almost any investment you can buy.','de deuda cara es una pérdida garantizada cada mes. Liquidarla le gana a casi cualquier inversión que puedas comprar.')}`, place: 'bank' });
  else if (expensiveBalance > 0) out.push({ id: 'expensive-debt-only', tone: 'tip', title: tl('Expensive debt first.','La deuda cara primero.'), text: `${money(expensiveBalance)} ${tl('at high interest is the most reliable return in the game: every dollar repaid stops costing you.','a interés alto es el rendimiento más seguro del juego: cada dólar pagado deja de costarte.')}`, place: 'bank' });
  if (investedValue > 0 && crypto / investedValue > .5) out.push({ id: 'crypto-heavy', tone: 'warn', title: tl('More than half your investments are crypto.','Más de la mitad de tus inversiones son cripto.'), text: tl('That is a bet, not a plan. A bad year can halve it. Index funds own hundreds of companies; keep the speculation small.','Eso es una apuesta, no un plan. Un mal año puede reducirlo a la mitad. Los fondos indexados poseen cientos de empresas; mantén pequeña la especulación.'), place: 'exchange' });
  if (lifestyleCost / income > .6) out.push({ id: 'lifestyle', tone: 'warn', title: tl('Your place eats most of your pay.','Tu casa se come casi todo tu sueldo.'), text: `${money(lifestyleCost)} ${tl('of','de')} ${money(income)} ${tl('goes to lifestyle every month. Nothing wrong with living well, but freedom is bought with the gap.','se va en estilo de vida cada mes. Vivir bien no está mal, pero la libertad se compra con la brecha.')}`, place: 'home' });
  if (buffer > expenses * 6 && investedValue < expenses) out.push({ id: 'idle-cash', tone: 'tip', title: tl('Your cushion is bigger than it needs to be.','Tu colchón es más grande de lo necesario.'), text: `${money(buffer)} ${tl('sits in cash and savings, more than six months of bills. Inflation quietly taxes it. Put the surplus to work a little at a time.','está en efectivo y ahorros, más de seis meses de facturas. La inflación lo grava en silencio. Pon el excedente a trabajar poco a poco.')}`, place: 'exchange' });
  if (state.month >= 6 && investedValue === 0 && state.cash >= expenses * 2) out.push({ id: 'never-invested', tone: 'tip', title: tl('Six months in and nothing is invested.','Seis meses y nada invertido.'), text: tl('Time is the ingredient you cannot buy back. Even $500 a month in an index fund compounds for decades.','El tiempo es el ingrediente que no se puede recomprar. Incluso $500 al mes en un fondo indexado se capitalizan durante décadas.'), place: 'exchange' });
  if ((state.marketCycle.phase === 'CONTRACTION' || state.economy.recession) && investedValue > 0) out.push({ id: 'dip', tone: 'tip', title: tl('This is the part where people panic.','Esta es la parte donde la gente entra en pánico.'), text: tl('Prices are down. Selling now turns a paper loss into a real one. If your bills are covered, the same money buys more units this month.','Los precios bajaron. Vender ahora convierte una pérdida en papel en una real. Si tus facturas están cubiertas, el mismo dinero compra más unidades este mes.'), place: 'exchange' });
  if (state.cafe && reputationOf(state.cafe) < 40) out.push({ id: 'cafe-rep', tone: 'warn', title: tl('The café has a reputation problem.','El café tiene un problema de reputación.'), text: `${tl('Word gets around at','Se corre la voz con')} ${reputationOf(state.cafe)}/100. ${tl('One good owner shift lifts it twelve points; a month behind the counter changes the year.','Un buen turno de dueño la sube doce puntos; un mes tras el mostrador cambia el año.')}`, place: 'cafe' });
  const outlook = promotionOutlook(state);
  if (outlook.eligible && outlook.next) out.push({ id: 'promotion', tone: 'tip', title: `${tl('You qualify for','Cumples los requisitos para')} ${outlook.next.title}. ${tl('Ask.','Pídelo.')}`, text: `${tl('Your manager will not bring it up. Each month you ask carries about a','Tu jefe no lo va a mencionar. Cada mes que preguntes hay cerca de un')} ${Math.round(outlook.chance * 100)}% ${tl('chance, and a raise compounds every month after it lands.','de probabilidad, y un aumento se capitaliza cada mes después de llegar.')}`, place: 'work' });
  const plan = studyPlan(state);
  if (outlook.next && !outlook.educationMet && !plan.enrolled) out.push({ id: 'study', tone: 'tip', title: `${outlook.next.title} ${tl('needs a qualification you do not have yet.','requiere un título que aún no tienes.')}`, text: `${tl('The college prices every course by payback.','El colegio valora cada curso por su retorno.')} ${plan.best ? `${plan.best.name} ${tl('pays for itself in about','se paga sola en unos')} ${plan.best.paybackMonths} ${tl('months.','meses.')}` : tl('Save the deposit for the cheapest step on your path.','Ahorra el anticipo del paso más barato de tu carrera.')}`, place: 'college' });
  else if (plan.best && plan.best.paybackMonths !== null && plan.best.paybackMonths <= 30 && !plan.enrolled) out.push({ id: 'quick-course', tone: 'tip', title: `${plan.best.name} ${tl('pays for itself in about','se paga sola en unos')} ${plan.best.paybackMonths} ${tl('months.','meses.')}`, text: `${money(plan.best.deposit)} ${tl('up front for about','por adelantado por unos')} ${money(plan.best.gainMonthly)} ${tl('more a month for the rest of your career. Few investments in the game pay back that fast.','más al mes por el resto de tu carrera. Pocas inversiones del juego se recuperan tan rápido.')}`, place: 'college' });
  const kids = household(state).children.find(c => c.canFund && c.fund === 0 && c.ageMonths >= 0 && c.fundMonthly > 0);
  if (kids && state.cash >= expenses * 2) out.push({ id: 'college-fund', tone: 'tip', title: `${kids.name} ${tl('turns 18 in','cumple 18 en')} ${kids.monthsTo18} ${tl('months.','meses.')}`, text: `${money(kids.fundMonthly)} ${tl('a month from now reaches the $60,000 dream-school bill; start later and the number climbs. Put it aside at home.','al mes desde hoy alcanza la cuenta de $60,000 de la universidad soñada; empieza después y la cifra sube. Apártalo en casa.')}`, place: 'home' });
  const health = offers(state).find(o => o.id === 'health');
  // Rosa leaves insurance alone during the opening months (the reserve comes first), then names the bill the player could not pay.
  if (health && !health.held && state.month >= 6 && state.cash < health.example.loss) out.push({ id: 'uninsured', tone: 'warn', title: tl('One surgery would empty your account.','Una cirugía vaciaría tu cuenta.'), text: `${tl('The biggest medical bill in this game is','La factura médica más grande de este juego es de')} ${money(health.example.loss)}; ${tl('your cash is','tu efectivo es')} ${money(state.cash)}. ${tl('Health cover at the bank turns it into','El seguro de salud del banco la convierte en')} ${money(health.example.withCover)} ${tl('for','por')} ${money(health.premium)} ${tl('a month.','al mes.')}`, place: 'bank' });
  if (state.cafe && !state.cafe.plan.open) out.push({ id: 'cafe-closed', tone: 'warn', title: tl('Closed shops still pay rent.','Las tiendas cerradas también pagan renta.'), text: tl('$720 a month leaves while the doors are shut. Reopen with a lean plan or end the lease; limbo is the expensive choice.','$720 al mes se van mientras las puertas están cerradas. Reabre con un plan austero o termina el contrato; el limbo es la opción cara.'), place: 'cafe' });
  if (passiveShare >= 1.1) out.push({ id: 'free', tone: 'good', title: tl('Your investments cover your life.','Tus inversiones cubren tu vida.'), text: `${tl('Passive income of','Los ingresos pasivos de')} ${money(flow.passive)} ${tl('a month clears','al mes cubren')} ${money(expenses)} ${tl('of bills with room to spare. Everything from here is choice.','de facturas con margen. Todo lo que sigue es elección.')}` });
  else if (passiveShare >= .25) out.push({ id: 'progress', tone: 'good', title: `${Math.round(passiveShare * 100)}% ${tl('of your bills are paid by money you do not work for.','de tus facturas las paga dinero por el que no trabajas.')}`, text: `${money(flow.passive)} a month arrives whether you show up or not. Keep the gap wide and that number grows on its own.` });
  if (!out.length) out.push({ id: 'steady', tone: 'good', title: tl('Nothing on fire.','Nada se está incendiando.'), text: 'Reserve intact, no expensive debt, a plan in motion. Boring months are where wealth is actually built. The notice board has three small things to do.', place: 'board' });
  return out.slice(0, 3);
}
export const adviceHeadline = (state: GameState) => adviseFrom(state)[0]?.title ?? '';
