import React from 'react';
import { tl } from '../../i18n/town';
import { CafeService, serviceTask, serviceReceipt, serviceStars, atServiceStation, SERVICE_STATIONS } from '../../services/cafeService';
export default function CafeServiceHUD({shift,practice,point,paused,onAct,onPause,onFinish}:{shift:CafeService;practice:boolean;point:{x:number;z:number};paused:boolean;onAct:()=>void;onPause:()=>void;onFinish:()=>void}) {
  const task=serviceTask(shift), receipt=serviceReceipt(shift),near=task&&atServiceStation(point,task.station);
  return <div className="town-service-hud" aria-label={tl('Hands-on café shift','Turno práctico en el café')}>
    <div className="town-service-score"><strong>{practice?tl('PRACTICE','PRÁCTICA'):tl('OWNER SHIFT','TURNO DEL DUEÑO')} · {receipt.served}/{shift.guests.length} {tl('served','atendidos')} · {'★'.repeat(serviceStars(shift))}{'☆'.repeat(3-serviceStars(shift))}</strong><span>{shift.elapsed}s · {shift.plan.stock-shift.prepared} {tl('fresh portions','porciones frescas')} · ${receipt.revenue} {tl('in','de ventas')}{receipt.tips?` (${tl('incl.','incl.')} $${receipt.tips} ${tl('tips','de propinas')})`:''}</span>{receipt.tips>0&&<em key={receipt.tips} className="town-tip-flash" aria-live="polite">{tl('Tip!','¡Propina!')} +${shift.guests.filter(g=>g.tip).at(-1)?.tip}</em>}<button onClick={onPause}>{paused?tl('Resume','Reanudar'):tl('Pause','Pausa')}</button></div>
    <div className="town-service-guests">{shift.guests.map(g=><div key={g.id} className={`town-guest-card guest-${g.status}`}><strong>{g.name} <span>{g.status==='served'?'✓':g.status==='left'?'↗':g.drink==='latte'?'☕':'●'}</span></strong><small>{g.status==='served'?(g.tip?`${tl('Happy','Contento')} · +$${g.tip} ${tl('tip','propina')}`:tl('Served','Atendido')):g.status==='left'?tl('Walked out','Se fue'):g.status==='coming'?tl('Arriving soon','Llega pronto'):`${g.drink}${g.helperTook?tl(' · helper',' · ayudante'):''} · ${Math.max(0,g.deadline-shift.elapsed)}s`}</small><progress max={g.deadline-g.arrival} value={g.status==='served'?g.deadline-g.arrival:g.status==='left'?0:Math.max(0,g.deadline-shift.elapsed)} aria-label={`${g.name} ${tl('patience','paciencia')}`}/></div>)}</div>
    <div className="town-service-action"><p>{paused?tl('Shift paused. Your guests keep their place.','Turno en pausa. Tus clientes guardan su lugar.'):task?.detail}</p><button className="town-primary" disabled={paused||(near&&task?.kind==='wait')} onClick={onAct}>{paused?tl('Resume to continue','Reanudar para continuar'):!task?tl('Shift complete','Turno completo'):near?task.verb:`${tl('Walk to','Ir a')} ${SERVICE_STATIONS[task.station].label} →`}</button><button className="town-service-end" onClick={onFinish}>{tl('Finish early · waiting guests leave','Terminar antes · los clientes en espera se van')}</button></div>
  </div>;
}
