import React, { useState } from 'react';
import { CafeService, ServicePlan, serviceCost, serviceReceipt, serviceStars, expectedGuests, patienceFor } from '../../services/cafeService';
import type { GameState } from '../../types';
import { reputationOf, REPUTATION_BY_STARS, reputationDemand } from '../../services/townCafe';
const money = (n:number) => `${n<0?'−':''}$${Math.abs(n)}`;
export default function CafeServicePanel({state,shift,practice,disabled,unavailable,onPractice,onStart,onResume,onExitPractice}:{state:GameState;shift?:CafeService;practice:boolean;disabled:boolean;unavailable:boolean;onPractice:(plan:ServicePlan)=>void;onStart:(plan:ServicePlan)=>void;onResume:()=>void;onExitPractice:()=>void}) {
  const [plan,setPlan]=useState<ServicePlan>({price:4,stock:6,helper:false,pace:'relaxed'});
  const receipt=shift&&serviceReceipt(shift),cost=serviceCost(plan),guests=expectedGuests(state.month,plan),stars=shift?serviceStars(shift):0;
  if(shift?.status==='active')return <section className="town-service-intro"><p className="town-eyebrow">{practice?'PRACTICE':'OWNER SHIFT'} · PAUSED</p><h3>Your guests are waiting.</h3><p>The timer pauses while this panel is open or you leave the café. Your position buttons walk you to the counter, machine and tables.</p><button className="town-primary" onClick={onResume}>Resume serving →</button></section>;
  return <section className="town-service-intro">
    <p className="town-eyebrow">{practice?'PRACTICE · NO MONEY CHANGES':'YOUR NEXT SHIFT'}</p><h3>{receipt?'What did you keep?':'Run a hands-on shift.'}</h3>
    {receipt&&<div className="town-recap" role="status"><h4>{practice?'Practice':'Owner shift'} · month {shift!.month} · {'★'.repeat(stars)}{'☆'.repeat(3-stars)}</h4><dl><div><dt>Happy guests / walked out</dt><dd>{receipt.served} / {receipt.left}</dd></div><div><dt>Sales</dt><dd>{money(receipt.revenue-receipt.tips)}</dd></div><div><dt>Tips for quick service</dt><dd>{money(receipt.tips)}</dd></div><div><dt>Fresh supplies</dt><dd>−{money(receipt.supplies)}</dd></div><div><dt>Helper pay + extra operating costs</dt><dd>−{money(receipt.wages+receipt.overhead)}</dd></div><div><dt>{receipt.profit<0?'Shift loss':'Shift profit'}</dt><dd>{money(receipt.profit)}</dd></div></dl><p>{receipt.wasted} cups’ worth of stock unused. You paid for all fresh stock, even when guests left.</p><p>{practice?'Practice only: your balance has not changed.':'Already included in your cash. Regular monthly café trading is separate; this shift will not pay again on month advance.'}</p>{receipt.left>0&&<p>Keep guests waiting less: take the next order while a drink brews, collect it from the machine, then deliver it. A helper takes orders for you and buys more patience, but takes a wage.</p>}{stars===3&&<p>Three stars: everyone served and most tipped. Try premium prices or the rush pace next.</p>}{!practice&&state.cafe&&<p>Café reputation is now {reputationOf(state.cafe)}/100 ({REPUTATION_BY_STARS[stars]>0?'+':''}{REPUTATION_BY_STARS[stars]} from this shift): {Math.round((reputationDemand(reputationOf(state.cafe))-1)*100)>=0?'+':''}{Math.round((reputationDemand(reputationOf(state.cafe))-1)*100)}% demand next month.</p>}{practice&&<p>Practice never moves your café's reputation; an owner shift does, by its stars.</p>}{receipt.profit<0&&<p>Sales are not profit. Compare the stock and staffing bill with the number of guests you can serve.</p>}</div>}
    {practice&&<button className="town-text-button" onClick={onExitPractice}>Leave practice results</button>}
    <p>Take orders, make coffee, collect each drink from the machine and carry it to its customer. Tap the next-step button to walk there, then tap again to act—or walk with the joystick and press E. Take the next order while a drink brews; serve within the first half of a guest's patience for a tip.</p>
    <fieldset><legend>Cup price</legend><div className="town-tabs">{([4,6] as const).map(price=><button key={price} aria-pressed={plan.price===price} onClick={()=>setPlan(p=>({...p,price}))}>${price} per drink</button>)}</div></fieldset>
    <fieldset><legend>Fresh supplies</legend><div className="town-tabs">{([3,6] as const).map(stock=><button key={stock} aria-pressed={plan.stock===stock} onClick={()=>setPlan(p=>({...p,stock}))}>{stock} drinks · ${stock*2}</button>)}</div></fieldset>
    <fieldset><legend>Help & pace</legend><div className="town-tabs"><button aria-pressed={plan.helper} onClick={()=>setPlan(p=>({...p,helper:!p.helper}))}>{plan.helper?'Helper on':'No helper'} · {plan.helper?'$3 extra':'$0'}</button><button aria-pressed={plan.pace==='relaxed'} onClick={()=>setPlan(p=>({...p,pace:p.pace==='relaxed'?'rush':'relaxed'}))}>{plan.pace==='relaxed'?'Relaxed pace':'Rush pace'}</button></div></fieldset>
    <p className="town-small">{guests} guests expected, each patient for about {patienceFor(plan)}s. ${cost} upfront: ${plan.stock*2} supplies + $3 extra operating costs{plan.helper?' + $3 helper pay (the helper takes orders)':''}. Break even at {Math.ceil(cost/plan.price)} drinks sold; quick service adds ${plan.price===6?2:1} tips. Premium customers expect faster service; fewer visit in rain. The timer pauses when you leave or hide the game.</p>
    <button className="town-primary" disabled={unavailable} onClick={()=>onPractice(plan)}>Try a practice shift · no money changes</button>
    {state.cafe&&<button className="town-service-paid" disabled={unavailable||disabled||!state.cafe.plan.open||state.cafe.service?.month===state.month||state.cash<cost} onClick={()=>onStart(plan)}>{state.cafe.service?.month===state.month?'Owner shift recorded for this month':`Open owner shift · commit $${cost}`}</button>}
    {unavailable&&<p className="town-small">Serving needs the 3D view to finish loading. Café management remains available.</p>}
    <p className="town-small">Practice is repeatable and unsaved. One paid extra owner shift per game month; its costs cannot be refunded by closing or reloading.</p>
  </section>;
}
