import React from 'react';
import { CafeService, serviceTask, serviceReceipt, serviceStars, atServiceStation, SERVICE_STATIONS } from '../../services/cafeService';
export default function CafeServiceHUD({shift,practice,point,paused,onAct,onPause,onFinish}:{shift:CafeService;practice:boolean;point:{x:number;z:number};paused:boolean;onAct:()=>void;onPause:()=>void;onFinish:()=>void}) {
  const task=serviceTask(shift), receipt=serviceReceipt(shift),near=task&&atServiceStation(point,task.station);
  return <div className="town-service-hud" aria-label="Hands-on café shift">
    <div className="town-service-score"><strong>{practice?'PRACTICE':'OWNER SHIFT'} · {receipt.served}/{shift.guests.length} served · {'★'.repeat(serviceStars(shift))}{'☆'.repeat(3-serviceStars(shift))}</strong><span>{shift.elapsed}s · {shift.plan.stock-shift.prepared} fresh portions · ${receipt.revenue} in{receipt.tips?` (incl. $${receipt.tips} tips)`:''}</span>{receipt.tips>0&&<em key={receipt.tips} className="town-tip-flash" aria-live="polite">Tip! +${shift.guests.filter(g=>g.tip).at(-1)?.tip}</em>}<button onClick={onPause}>{paused?'Resume':'Pause'}</button></div>
    <div className="town-service-guests">{shift.guests.map(g=><div key={g.id} className={`town-guest-card guest-${g.status}`}><strong>{g.name} <span>{g.status==='served'?'✓':g.status==='left'?'↗':g.drink==='latte'?'☕':'●'}</span></strong><small>{g.status==='served'?(g.tip?`Happy · +$${g.tip} tip`:'Served'):g.status==='left'?'Walked out':g.status==='coming'?'Arriving soon':`${g.drink}${g.helperTook?' · helper':''} · ${Math.max(0,g.deadline-shift.elapsed)}s`}</small><progress max={g.deadline-g.arrival} value={g.status==='served'?g.deadline-g.arrival:g.status==='left'?0:Math.max(0,g.deadline-shift.elapsed)} aria-label={`${g.name} patience`}/></div>)}</div>
    <div className="town-service-action"><p>{paused?'Shift paused. Your guests keep their place.':task?.detail}</p><button className="town-primary" disabled={paused||(near&&task?.kind==='wait')} onClick={onAct}>{paused?'Resume to continue':!task?'Shift complete':near?task.verb:`Walk to ${SERVICE_STATIONS[task.station].label} →`}</button><button className="town-service-end" onClick={onFinish}>Finish early · waiting guests leave</button></div>
  </div>;
}
