import React, { useEffect, useState } from 'react';
import { tl, isSpanish } from '../../i18n/town';
import { incidentCopyEs } from '../../services/townCafe';
import type { GameState } from '../../types';
import { CafeAction, CafePlan, CafeReceipt, CAFE_DEPOSIT, CAFE_FITOUT, CAFE_UPGRADES, cafeValue, canLeaseCafe, quoteCafe, reputationOf, reputationDemand, reputationLabel } from '../../services/townCafe';
import { calculateMonthlyCashFlowEstimate } from '../../services/gameLogic';
const money = (n: number) => `${n < 0 ? '−' : ''}$${Math.abs(n).toLocaleString('en-US')}`;
export function CafeLedger({ receipt }: { receipt: CafeReceipt }) {
  return <div className="town-recap"><h4>{tl('Month','Mes')} {receipt.month} · {receipt.rainy ? tl('Rainy & quieter','Lluvia y menos gente') : tl('Market crowds','Multitudes de mercado')}</h4><dl>
    <div><dt>{tl('Cups sold / stocked','Tazas vendidas / surtidas')}</dt><dd>{receipt.sold} / {receipt.stock}</dd></div>
    <div><dt>{tl('Sales','Ventas')}</dt><dd>{money(receipt.revenue)}</dd></div>
    <div><dt>{tl('All fresh supplies','Todos los suministros frescos')}</dt><dd>−{money(receipt.supplies)}</dd></div>
    <div><dt>{tl('Staff wages','Sueldos del personal')}</dt><dd>−{money(receipt.wages)}</dd></div>
    <div><dt>{tl('Rent + utilities','Renta + servicios')}</dt><dd>−{money(receipt.rent + receipt.utilities)}</dd></div>
    <div><dt>{receipt.profit < 0 ? tl('Operating loss','Pérdida operativa') : tl('Operating profit','Ganancia operativa')}</dt><dd>{money(receipt.profit)}</dd></div>
  </dl>{receipt.incidents?.length ? <ul className="town-incidents">{receipt.incidents.map(i => <li key={i.id}><strong>{isSpanish() ? incidentCopyEs[i.id].title : i.title}</strong> {isSpanish() ? incidentCopyEs[i.id].detail : i.detail} {i.cost > 0 ? `−$${i.cost}.` : i.cost < 0 ? `+$${-i.cost}.` : ''}{i.reputation ? ` ${tl('Reputation','Reputación')} ${i.reputation > 0 ? '+' : ''}${i.reputation}.` : ''}</li>)}</ul> : null}<p>{receipt.stock - receipt.sold} {tl('cups’ worth of supplies wasted. Net operating profit is already part of monthly income; these costs are not deducted twice. Annual game taxes are separate.','tazas de suministros desperdiciadas. La ganancia operativa neta ya forma parte del ingreso mensual; estos costos no se descuentan dos veces. Los impuestos anuales del juego son aparte.')}</p></div>;
}
export default function CafePanel({ state, disabled, onAction, onNextMonth }: { state: GameState; disabled: boolean; onAction?: (action: CafeAction) => void; onNextMonth: () => void }) {
  const cafe = state.cafe;
  const [plan, setPlan] = useState<CafePlan>(cafe?.plan ?? { price: 6, stock: 400, helper: false, open: true });
  const [confirmClose, setConfirmClose] = useState(false), [notice, setNotice] = useState('');
  useEffect(() => { if (cafe) setPlan(cafe.plan); setConfirmClose(false); }, [cafe]);
  const locked = disabled || !onAction;
  if (!cafe) return <section className="town-cafe-panel"><p className="town-eyebrow">{tl('THE NEXT CHAPTER','EL SIGUIENTE CAPÍTULO')}</p><h3>{tl('From cart to café.','Del carrito al café.')}</h3><p className="town-intro">{tl('Your own neighbourhood shop. Start with a counter and one barista, then add seating and better equipment when the numbers make sense.','Tu propio local en el barrio. Empieza con un mostrador y un barista, y agrega asientos y mejor equipo cuando los números tengan sentido.')}</p>
    <div className="town-lesson"><strong>{tl('Move in for','Múdate por')} {money(CAFE_DEPOSIT + CAFE_FITOUT)}</strong><p>{money(CAFE_DEPOSIT)} {tl('refundable deposit +','de depósito reembolsable +')} {money(CAFE_FITOUT)} {tl('fit-out. The fit-out has a $600 resale value. Rent is $600/month and utilities $120/month, even when closed.','de acondicionamiento. El acondicionamiento tiene un valor de reventa de $600. La renta es $600/mes y los servicios $120/mes, incluso cerrado.')}</p><p>{tl('While open: $600/month for one barista, plus $2 for every cup stocked. First bills and sales arrive when you advance the month. Your cart keeps trading separately.','Abierto: $600/mes por un barista, más $2 por cada taza surtida. Las primeras facturas y ventas llegan al avanzar el mes. Tu carrito sigue vendiendo aparte.')}</p><p>{tl('Cash after moving in','Efectivo después de mudarte')}: <strong>{money(state.cash - CAFE_DEPOSIT - CAFE_FITOUT)}</strong>. {tl('Keep money for personal bills and the café’s opening stock and wages.','Guarda dinero para tus facturas personales y para el surtido y los sueldos iniciales del café.')}</p></div>
    {!canLeaseCafe(state) && <p className="town-cafe-warning">{tl('First own a licensed cart and complete one owner’s shift. You can explore this room while working toward it.','Primero ten un carrito con licencia y completa un turno de dueño. Puedes explorar este local mientras lo consigues.')}</p>}
    <button className="town-primary" disabled={locked || !canLeaseCafe(state) || state.cash < 3000} onClick={() => onAction?.({ type: 'lease' })}>{tl('Lease & fit out café · $3,000','Rentar y acondicionar el café · $3,000')}</button>
  </section>;
  const quote = quoteCafe({ ...cafe, plan }, state.month + 1), saved = JSON.stringify(plan) === JSON.stringify(cafe.plan);
  const reserve = calculateMonthlyCashFlowEstimate(state).expenses + quote.costs;
  const change = (patch: Partial<CafePlan>) => { setPlan(p => ({ ...p, ...patch })); setNotice(''); };
  const reputation = reputationOf(cafe), demandPct = Math.round((reputationDemand(reputation) - 1) * 100), shiftDone = cafe.service?.month === state.month;
  return <section className="town-cafe-panel"><p className="town-eyebrow">{tl('YOUR CAFÉ · MONTHLY MANAGEMENT','TU CAFÉ · GESTIÓN MENSUAL')}</p><h3>{tl('A place of your own.','Un lugar propio.')}</h3><p>{tl('Your saved plan repeats each month. Staff run the counter; you choose what to spend and what to charge.','Tu plan guardado se repite cada mes. El personal atiende el mostrador; tú eliges cuánto gastar y cuánto cobrar.')}</p>
    <div className="town-lesson town-reputation" aria-label={tl('Café reputation','Reputación del café')}><strong>{tl('Reputation','Reputación')} {reputation}/100 · {reputationLabel(reputation)}</strong><div className="town-reputation-bar" role="img" aria-label={`${reputation} ${tl('out of 100','de 100')}`}><span style={{ width: `${reputation}%` }} /></div><p>{demandPct === 0 ? tl('Average: no effect on demand yet.','Promedio: sin efecto en la demanda todavía.') : `${demandPct > 0 ? '+' : ''}${demandPct}% ${tl('demand next month.','de demanda el próximo mes.')}`} {shiftDone ? tl('This month’s owner shift is already counted.','El turno de dueño de este mes ya está contado.') : tl('A three-star owner shift lifts it by 12; a poor one costs 12. Months without you behind the counter drift it back toward 50.','Un turno de dueño de tres estrellas la sube 12; uno malo la baja 12. Los meses sin ti tras el mostrador la acercan de nuevo a 50.')}</p></div>
    <fieldset><legend>{tl('Trading','Operación')}</legend><div className="town-tabs"><button aria-pressed={plan.open} onClick={() => change({ open: true })}>{tl('Open','Abierto')}</button><button aria-pressed={!plan.open} onClick={() => change({ open: false })}>{tl('Temporarily closed','Cerrado temporalmente')}</button></div></fieldset>
    <fieldset disabled={!plan.open}><legend>{tl('Cup price','Precio por taza')}</legend><div className="town-tabs">{([4, 6] as const).map(price => <button key={price} aria-pressed={plan.price === price} onClick={() => change({ price })}>${price} {tl('per cup','por taza')}</button>)}</div></fieldset>
    <fieldset disabled={!plan.open}><legend>{tl('Monthly fresh stock','Surtido fresco mensual')}</legend><div className="town-tabs">{([400, 700] as const).map(stock => <button key={stock} aria-pressed={plan.stock === stock} onClick={() => change({ stock })}>{stock} {tl('cups','tazas')} · ${stock * 2}</button>)}</div></fieldset>
    <fieldset disabled={!plan.open}><legend>{tl('Staff','Personal')}</legend><div className="town-tabs"><button aria-pressed={!plan.helper} onClick={() => change({ helper: false })}>{tl('One barista · $600','Un barista · $600')}</button><button aria-pressed={plan.helper} onClick={() => change({ helper: true })}>{tl('Two staff · $1,000','Dos empleados · $1,000')}</button></div></fieldset>
    <div className="town-lesson"><strong>{tl('Next month','Próximo mes')}: {quote.rainy ? tl('rain & lighter foot traffic','lluvia y menos gente') : tl('busy market days','días de mercado concurridos')}</strong><p>{quote.demand} {tl('potential buyers · capacity','compradores potenciales · capacidad')} {quote.capacity} {tl('cups. Forecast','tazas. Pronóstico')}: <strong>{quote.sold} {tl('sales','ventas')}, {money(quote.profit)} {quote.profit < 0 ? tl('loss','de pérdida') : tl('profit','de ganancia')}</strong>.</p><p>{money(quote.costs)} {tl('total operating costs. Break even at','de costos operativos totales. Punto de equilibrio en')} {Math.ceil(quote.costs / plan.price)} {tl('cups sold.','tazas vendidas.')} {quote.stock - quote.sold} {tl('cups’ worth of stock would be wasted.','tazas de surtido se desperdiciarían.')}</p><p>{tl('This teaching forecast uses fixed demand so you can see each decision’s effect. Prices, staffing and upgrades do not guarantee profit.','Este pronóstico didáctico usa demanda fija para que veas el efecto de cada decisión. Precios, personal y mejoras no garantizan ganancia.')}</p></div>
    {state.cash < reserve && <p className="town-cafe-warning">{tl('Thin cash reserve','Reserva de efectivo escasa')}: {money(reserve)} {tl('would cover one month of personal bills plus café costs before sales arrive. You have','cubriría un mes de facturas personales más los costos del café antes de que lleguen las ventas. Tienes')} {money(state.cash)}.</p>}
    <button className="town-primary" disabled={locked || saved} onClick={() => { onAction?.({ type: 'plan', plan }); setNotice(tl('Plan saved. It takes effect next month.','Plan guardado. Surte efecto el próximo mes.')); }}>{saved ? tl('Next month’s plan saved','Plan del próximo mes guardado') : tl('Save next month’s plan','Guardar el plan del próximo mes')}</button>
    {notice && <p role="status" className="town-receipt">{notice}</p>}
    <h4>{tl('Make the space yours','Haz tuyo el espacio')}</h4>{!saved && <p className="town-small">{tl('Save the plan before installing upgrades.','Guarda el plan antes de instalar mejoras.')}</p>}<div className="town-cafe-upgrades">{(['seats', 'machine'] as const).map(upgrade => <article key={upgrade}><strong>{upgrade === 'seats' ? tl('Cosy seating','Asientos acogedores') : tl('Espresso machine','Máquina de espresso')}</strong><p>{upgrade === 'seats' ? tl('+80 potential buyers/month. Tables and chairs appear in your shop.','+80 compradores potenciales al mes. Aparecen mesas y sillas en tu local.') : tl('+150 cups of monthly capacity. A larger machine appears behind the counter.','+150 tazas de capacidad mensual. Aparece una máquina más grande tras el mostrador.')}</p><button disabled={locked || !saved || cafe[upgrade] || state.cash < CAFE_UPGRADES[upgrade]} onClick={() => onAction?.({ type: 'upgrade', upgrade })}>{cafe[upgrade] ? tl('Installed ✓','Instalado ✓') : `${tl('Install','Instalar')} · ${money(CAFE_UPGRADES[upgrade])}`}</button></article>)}</div>
    {cafe.lastReceipt ? <CafeLedger receipt={cafe.lastReceipt} /> : <p className="town-small">{tl('Your first trading receipt arrives next month.','Tu primer recibo de ventas llega el próximo mes.')}</p>}
    <button className="town-primary" disabled={disabled || !saved} onClick={onNextMonth}>{tl('Review next month →','Revisar el próximo mes →')}</button>{!saved && <p>{tl('Save your plan before advancing.','Guarda tu plan antes de avanzar.')}</p>}
    <p className="town-small">{tl('Deposit and equipment resale worth','El depósito y la reventa del equipo por')} {money(cafeValue(cafe))} {tl('are included in net worth. Closing recovers that amount; fit-out losses are real.','están incluidos en el patrimonio. Cerrar recupera ese monto; las pérdidas del acondicionamiento son reales.')}</p>
    {confirmClose ? <div className="town-lesson"><strong>{tl('End the lease for','¿Terminar el contrato y recuperar')} {money(cafeValue(cafe))}{tl(' back?','?')}</strong><p>{tl('The café closes and its future bills stop. You lose this fit-out and its upgrades. Your cart stays yours.','El café cierra y sus facturas futuras se detienen. Pierdes este acondicionamiento y sus mejoras. Tu carrito sigue siendo tuyo.')}</p><button disabled={locked} onClick={() => onAction?.({ type: 'close' })}>{tl('End lease & return keys','Terminar contrato y devolver llaves')}</button><button onClick={() => setConfirmClose(false)}>{tl('Keep my café','Conservar mi café')}</button></div> : <button className="town-text-button" disabled={locked} onClick={() => setConfirmClose(true)}>{tl('Consider ending the lease','Considerar terminar el contrato')}</button>}
  </section>;
}
