import React, {useState} from 'react';
import { tl } from '../../i18n/town';
const weatherName=(w:string)=>w==='Rainy afternoon'?tl(w,'Tarde lluviosa'):w==='Busy market afternoon'?tl(w,'Tarde de mercado concurrida'):w;
import {GameState} from '../../types';
import {CartPlan, quoteCartShift} from '../../services/townActivities';
const money=(n:number)=>`${n<0?'−':''}$${Math.abs(n)}`;
export default function CartShiftPanel({state,disabled,onRun}:{state:GameState;disabled:boolean;onRun?:(plan:CartPlan)=>void}){
  const [price,setPrice]=useState<3|5>(5),[stock,setStock]=useState<12|24>(12);
  const quote=quoteCartShift(state,{price,stock}),receipt=state.townProgress?.lastShift;
  const complete=receipt?.month===state.month;
  return <section className="town-shift">
    <p className="town-eyebrow">{tl('AT YOUR CART · OWNER\'S SHIFT','EN TU CARRITO · TURNO DEL DUEÑO')}</p><h3>{complete?tl('You traded. What did you keep?','Vendiste. ¿Qué te quedó?'):tl('Open for an afternoon.','Abre por una tarde.')}</h3>
    <p className="town-intro">{tl('One extra pop-up shift each month. You choose the price and fresh stock; a customer visit plays out in the square.','Un turno extra cada mes. Eliges el precio y el surtido fresco; una visita de clientes ocurre en la plaza.')}</p>
    {complete&&receipt?<div className="town-recap"><h4>{tl('Month','Mes')} {receipt.month} · {weatherName(receipt.weather)}</h4><dl><div><dt>{tl('Cups sold','Tazas vendidas')}</dt><dd>{receipt.sold} / {receipt.stock}</dd></div><div><dt>{tl('Sales','Ventas')}</dt><dd>{money(receipt.revenue)}</dd></div><div><dt>{tl('Supplies ($2 per cup stocked)','Suministros ($2 por taza surtida)')}</dt><dd>−${receipt.stock*2}</dd></div><div><dt>{tl('Shift staffing & stall fee','Personal del turno y cuota del puesto')}</dt><dd>−$18</dd></div><div><dt>{receipt.profit<0?tl('Loss deducted from cash','Pérdida descontada del efectivo'):tl('Profit added to cash','Ganancia sumada al efectivo')}</dt><dd>{money(receipt.profit)}</dd></div></dl><p>{receipt.stock-receipt.sold} {tl('unsold cups\' worth of fresh supplies were wasted. Sales are not profit: you paid for every cup stocked.','tazas sin vender de suministros frescos se desperdiciaron. Las ventas no son ganancia: pagaste cada taza surtida.')}</p><p>{tl('This extra shift is already included in your cash. Regular monthly cart profit is separate. Review next month to unlock another shift.','Este turno extra ya está incluido en tu efectivo. La ganancia mensual normal del carrito es aparte. Revisa el próximo mes para desbloquear otro turno.')}</p></div>:<>
      <div className="town-lesson"><strong>{weatherName(quote.weather)}</strong><p>{state.month%3===0?tl('Foot traffic is lower. Weather cover helps demand, but fresh stock can still go unsold.','Hay menos gente. El toldo ayuda a la demanda, pero el surtido fresco aún puede quedarse sin vender.'):tl('Market visitors are passing by. Higher prices mean fewer buyers in this teaching example.','Los visitantes del mercado pasan por aquí. En este ejemplo didáctico, precios más altos significan menos compradores.')}</p></div>
      <fieldset><legend>{tl('1. Set your cup price','1. Fija el precio por taza')}</legend><div className="town-tabs">{([3,5] as const).map(n=><button key={n} aria-pressed={price===n} onClick={()=>setPrice(n)}>${n} {tl('per cup','por taza')}</button>)}</div></fieldset>
      <fieldset><legend>{tl('2. Choose fresh stock','2. Elige el surtido fresco')}</legend><div className="town-tabs">{([12,24] as const).map(n=><button key={n} aria-pressed={stock===n} onClick={()=>setStock(n)}>{n} {tl('cups','tazas')} · ${n*2}</button>)}</div></fieldset>
      <div className="town-lesson"><strong>{tl('Commit','Compromete')} ${quote.costs} {tl('before opening','antes de abrir')}</strong><p>${stock*2} {tl('supplies','de suministros')} + $18 {tl('shift costs. Break even at','de costos del turno. Punto de equilibrio en')} {Math.ceil(quote.costs/price)} {tl('cups sold','tazas vendidas')}{Math.ceil(quote.costs/price)>stock?tl('—more than you have stocked. This plan cannot make a profit.','—más de las que surtiste. Este plan no puede dar ganancia.'):'.'} {tl('Unsold supplies cannot be refunded.','Los suministros sin vender no se reembolsan.')}</p><p>{tl('Teaching forecast','Pronóstico didáctico')}: {quote.sold} {tl('sales','ventas')}, {money(quote.profit)} {quote.profit<0?tl('loss','de pérdida'):tl('profit','de ganancia')}. {tl('This preview uses fixed demand to make the trade-off visible.','Esta vista previa usa demanda fija para hacer visible la disyuntiva.')}</p></div>
      <button className="town-primary" disabled={disabled||state.cash<quote.costs||!onRun} onClick={()=>onRun?.({price,stock})}>{tl('Open pop-up shift · commit','Abrir turno · comprometer')} ${quote.costs}</button>
      <p className="town-small">{tl('Extra owner-run activity, separate from regular monthly operations. Opening settles the shift once, including any loss.','Actividad extra del dueño, aparte de la operación mensual normal. Abrir liquida el turno una vez, incluida cualquier pérdida.')}</p>
    </>}
  </section>;
}
