import React from 'react';
import { tl, isSpanish } from '../../i18n/town';

export type GuideLocation = 'bank'|'cafe'|'exchange'|'property'|'home'|'work'|'college'|'garage'|'board'|'rosa'|'business'|'cart';
// The guide describes the existing economy, never awards a reward itself.
export function locationGuide(location: GuideLocation) {
  const copy: Record<GuideLocation, [string,string,string,string]> = {
    bank: ['Plan and protect your money', 'Talk to the teller to deposit, withdraw, compare loans or insurance.', 'Transfers move your game money between accounts. Savings earns interest as months advance. Confirming a reserve is a planning milestone and moves no money.', 'Planning · game money'],
    cafe: ['Serve for fun, or run a business', 'Choose Practice to learn: take an order, brew, collect and deliver. Choose Manage café to review the lease and monthly plan.', 'Practice is free and changes no cash or reputation. An owner shift pays its costs upfront and credits sales once when finished; stars affect reputation. Regular café profit or loss is settled separately each month.', 'Free practice / business income'],
    exchange: ['Invest for future income', 'Talk to the broker, compare risk and price, then choose the amount to buy or sell.', 'Buying spends game cash; selling returns the current sale value. Holdings can lose value. Payments and price changes are separate, and future returns are not guaranteed.', 'Game money · investment risk'],
    property: ['Become a landlord', 'Talk to the agent to compare a property, its running costs and a cash purchase or mortgage.', 'A purchase uses cash now; a mortgage also adds repayments. Rent, upkeep, vacancies and tax affect later monthly results. Entering the office buys nothing.', 'Game money · monthly income and costs'],
    home: ['Make life fit your budget', 'Use your desk to review bills, compare lifestyles, manage side work and set money aside for family.', 'Lifestyle changes affect your living costs and happiness. Side work has its own costs and income. Visiting home gives no cash reward; review each action before choosing it.', 'Budget · wellbeing · side income'],
    work: ['Build your career', 'Talk to your manager to check pay, promotion requirements, career options and this month’s work actions.', 'Work actions share the dashboard’s monthly limit and can cost energy or cash. Overtime adds a bonus next month. A raise or promotion changes future pay; simply visiting does not pay a shift wage.', 'Salary · skills · energy'],
    college: ['Learn something that pays off', 'Talk to the registrar to compare fees, study time and whether a course fits your career. Self-study courses are available from the course panel.', 'Enrolment spends game money and may add a student loan. Relevant qualifications can raise pay when completed; unrelated courses do not. Read the specific certificate perk before studying.', 'Learning · tuition · future pay'],
    garage: ['Know what your car costs', 'Review your vehicle and compare buying, financing or selling at the parking bay.', 'Buying uses cash; financing adds a deposit and repayments. Cars also have running costs and resale values. This is vehicle management, not a driving race or points activity.', 'Game money · transport costs'],
    board: ['See what progress earns', 'Read this month’s challenges and your quests. Use Claim when a quest reward is ready.', 'Monthly challenges earn badges when the month closes, not cash. Quests award only the cash or stat rewards shown on their cards when claimed. Reviewing the next month advances the whole game economy.', 'Badges / named quest rewards'],
    rosa: ['Get a second opinion', 'Read Rosa’s advice and choose a suggested destination to investigate it.', 'Advice is free. Talking gives no cash or points; you decide whether to take the suggested action and its costs are shown at the destination.', 'Free advice'],
    business: ['Start small, then grow', 'Compare businesses here, visit the café, or buy a coffee cart and meet it in the square.', 'Buying spends game cash. The first cart needs a separate $60 permit before it earns income. Business income arrives as game months advance and can vary; purchases are not free unlocks.', 'Game money · business ownership'],
    cart: ['Work your coffee cart', 'Get the trading permit, choose your shift plan and review supplies before serving.', 'The permit costs $60 once. A manual shift has its own costs and receipt; ordinary monthly cart income is separate. Weather cover reduces risk but does not guarantee more profit.', 'Game money · shift profit or loss'],
  };
  const spanish: Record<GuideLocation, [string,string,string,string]> = {
    bank: ['Organiza y protege tu dinero', 'Habla con el cajero para depositar, retirar o comparar préstamos y seguros.', 'Las transferencias mueven tu dinero del juego entre cuentas. Los ahorros generan intereses al avanzar los meses. Confirmar una reserva es una meta de planificación y no mueve dinero.', 'Planificación · dinero del juego'],
    cafe: ['Sirve por diversión o dirige un negocio', 'Elige Práctica para aprender: toma un pedido, prepara el café, recógelo y entrégalo. Elige Administrar café para revisar el alquiler y el plan mensual.', 'La práctica es gratis y no cambia tu efectivo ni reputación. Un turno como propietario cobra los costos al inicio y acredita las ventas una sola vez al terminar; las estrellas afectan la reputación. La ganancia o pérdida habitual del café se calcula por separado cada mes.', 'Práctica gratis / ingresos del negocio'],
    exchange: ['Invierte para generar ingresos futuros', 'Habla con el corredor, compara el riesgo y el precio, y elige cuánto comprar o vender.', 'Comprar gasta efectivo del juego; vender devuelve el valor actual de venta. Las inversiones pueden perder valor. Los pagos y los cambios de precio son distintos; no se garantizan rendimientos futuros.', 'Dinero del juego · riesgo de inversión'],
    property: ['Conviértete en arrendador', 'Habla con el agente para comparar propiedades, sus gastos y una compra al contado o con hipoteca.', 'La compra usa efectivo ahora; la hipoteca también añade cuotas. La renta, el mantenimiento, las vacancias y los impuestos afectan los resultados mensuales. Entrar en la oficina no compra nada.', 'Dinero del juego · ingresos y gastos mensuales'],
    home: ['Ajusta tu vida a tu presupuesto', 'Usa tu escritorio para revisar facturas, comparar estilos de vida, administrar trabajos extra y ahorrar para tu familia.', 'El estilo de vida afecta los gastos y la felicidad. Los trabajos extra tienen sus propios costos e ingresos. Visitar tu casa no da efectivo; revisa cada acción antes de elegirla.', 'Presupuesto · bienestar · ingresos extra'],
    work: ['Desarrolla tu carrera', 'Habla con tu jefe para revisar sueldo, requisitos de ascenso, opciones de carrera y acciones laborales del mes.', 'Las acciones comparten el límite mensual del panel principal y pueden gastar energía o efectivo. Las horas extra añaden un bono el próximo mes. Un aumento o ascenso cambia el sueldo futuro; la visita por sí sola no paga un turno.', 'Sueldo · habilidades · energía'],
    college: ['Aprende algo que valga la pena', 'Habla con la secretaria para comparar matrícula, tiempo de estudio y relación con tu carrera. El panel de cursos también ofrece autoestudio.', 'Inscribirte gasta dinero del juego y puede añadir un préstamo estudiantil. Las credenciales relacionadas pueden aumentar tu sueldo al completarse; las que no corresponden a tu carrera no lo hacen. Lee el beneficio de cada certificado antes de estudiar.', 'Aprendizaje · matrícula · sueldo futuro'],
    garage: ['Conoce el costo de tu auto', 'Revisa tu vehículo y compara comprar, financiar o vender en la cochera.', 'Comprar usa efectivo; financiar añade un pago inicial y cuotas. Los autos también tienen gastos de uso y un valor de reventa. Aquí administras vehículos; no es una carrera ni una actividad de puntos.', 'Dinero del juego · transporte'],
    board: ['Descubre qué ganas al progresar', 'Lee los retos del mes y tus misiones. Usa Reclamar cuando una recompensa esté lista.', 'Los retos mensuales dan insignias al cerrar el mes, no efectivo. Las misiones dan únicamente el efectivo o las mejoras indicadas al reclamarlas. Avanzar al próximo mes mueve toda la economía del juego.', 'Insignias / recompensas de misiones'],
    rosa: ['Pide una segunda opinión', 'Lee el consejo de Rosa y elige un destino sugerido para investigarlo.', 'El consejo es gratis. Hablar no da dinero ni puntos; tú decides si realizas la acción sugerida y sus costos se muestran en el destino.', 'Consejo gratis'],
    business: ['Empieza pequeño y crece', 'Compara negocios aquí, visita el café o compra un carrito de café y búscalo en la plaza.', 'Comprar gasta efectivo del juego. El primer carrito necesita un permiso de $60 por separado antes de generar ingresos. Los ingresos llegan al avanzar los meses y pueden variar; las compras no son desbloqueos gratis.', 'Dinero del juego · negocios'],
    cart: ['Trabaja en tu carrito de café', 'Obtén el permiso comercial, elige el plan del turno y revisa los suministros antes de servir.', 'El permiso cuesta $60 una sola vez. Un turno manual tiene sus propios costos y recibo; los ingresos mensuales habituales son aparte. La protección contra el clima reduce el riesgo, pero no garantiza más ganancia.', 'Dinero del juego · ganancia o pérdida del turno'],
  };
  return isSpanish()?spanish[location]:copy[location];
}
export default function TownLocationGuide({location,onContinue,label,compact=false}:{location:GuideLocation;onContinue?:()=>void;label?:string;compact?:boolean}) {
  const [title,how,outcome,kind]=locationGuide(location);
  return <section className={`town-purpose${compact?' town-purpose-compact':''}`} aria-label={tl('What you can do here','Qué puedes hacer aquí')}>
    <p className="town-eyebrow">{kind}</p><h3>{title}</h3>
    <p><strong>{tl('How to play','Cómo jugar')}</strong> {how}</p>
    <p><strong>{tl('What changes','Qué cambia')}</strong> {outcome}</p>
    {onContinue&&<button className="town-primary" onClick={onContinue}>{label} →</button>}
    {!compact&&<p className="town-small">{tl('Exploring is free. All money here belongs to your saved game.','Explorar es gratis. Todo el dinero aquí pertenece a tu partida guardada.')}</p>}
  </section>;
}
